/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as MediaIndexRouteImport } from './routes/media/index'
import { Route as PostsNewRouteImport } from './routes/posts/new'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as ApiPostsIdRouteImport } from './routes/api/posts.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsNewRoute = PostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIdRoute = ApiPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/new': typeof PostsNewRoute
  '/media/': typeof MediaIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/new': typeof PostsNewRoute
  '/media': typeof MediaIndexRoute
  '/posts': typeof PostsIndexRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/new': typeof PostsNewRoute
  '/media/': typeof MediaIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/posts'
    | '/api/upload'
    | '/posts/$postId'
    | '/posts/new'
    | '/media/'
    | '/posts/'
    | '/api/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/posts'
    | '/api/upload'
    | '/posts/$postId'
    | '/posts/new'
    | '/media'
    | '/posts'
    | '/api/posts/$id'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/api/posts'
    | '/api/upload'
    | '/posts/$postId'
    | '/posts/new'
    | '/media/'
    | '/posts/'
    | '/api/posts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ApiPostsRoute: typeof ApiPostsRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsNewRoute: typeof PostsNewRoute
  MediaIndexRoute: typeof MediaIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/new': {
      id: '/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof PostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/$id': {
      id: '/api/posts/$id'
      path: '/$id'
      fullPath: '/api/posts/$id'
      preLoaderRoute: typeof ApiPostsIdRouteImport
      parentRoute: typeof ApiPostsRoute
    }
  }
}

interface ApiPostsRouteChildren {
  ApiPostsIdRoute: typeof ApiPostsIdRoute
}

const ApiPostsRouteChildren: ApiPostsRouteChildren = {
  ApiPostsIdRoute: ApiPostsIdRoute,
}

const ApiPostsRouteWithChildren = ApiPostsRoute._addFileChildren(
  ApiPostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ApiPostsRoute: ApiPostsRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  PostsNewRoute: PostsNewRoute,
  MediaIndexRoute: MediaIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
